### PR TITLE
Add a counter to the flip game.

### PR DESCRIPTION
**Pull request by ghost**
Add a counter to the flip game.
At the top of screen with messages such as keep going/good work ,total number of flips done till now is also prompted.

### CODE REVIEW

**Comment by ghost** [comment]
kindly review @chimosky @walterbender

**Comment by chimosky** [comment]
Tested, what's the use of the flip counter and it's at the activity toolbar which makes it very difficult to notice.

**Comment by ghost** [comment]
It gives a idea how much try it took you to reach the all sides though my initial plan was to make proper accuracy table because I think how much moves it took you to reach correct answer and then reducing it further gives you another motive to keep playing.
I included it at the top with message because first it was easy to implement it and also as message changes people might notice it not sure though.

**Comment by ghost** [comment]
Kindly also see these changes @quozl if these changes makes any sense?

**Comment by quozl** [comment]
Tested.  I don't see any counter.

**Comment by ghost** [comment]
Its at the top left side corner where two message are good work and keep trying but if you havent noticed that means its hard to notice it, well I think then accuracy table would be good idea?

**Comment by chimosky** [comment]
> Its at the top left side corner where two message are good work and keep trying but if you havent noticed that means its hard to notice it, well I think then accuracy table would be good idea?

An accuracy table wouldn't make much difference if it's difficult to see it, any game feature you plan to implement would be better shown on the activity canvas and not the activity toolbar.

> I included it at the top with message because first it was easy to implement it and also as message changes people might notice it not sure though.

An easy implementation is a great way to start a feature, took me awhile to see the messages because of their position so that means it'll be near impossible for anyone to see.

**Comment by ghost** [comment]
Yes, the accuracy table will in activity canvas,in activity toolbar its very difficult to see.

**Comment by quozl** [comment]
Still can't see it.  Is it my resolution?  Got a screenshot?

**Comment by ghost** [comment]
Screenshot 2024-03-28 at 2 03 35 PM
Screenshot 2024-03-28 at 2 03 25 PM
its there

**Comment by ghost** [comment]
Its counting double though..

**Comment by quozl** [comment]
Could you edit your commit message to (a) add why the change is being done, and (b) don't mention the flip game, it's obvious given the repository in which the commit will exist.

**Comment by ghost** [comment]
Ok I will edit message here, but I am thinking about generating another pr with the following features if mentors/developer agree :

- [ ] making a table like thing in activity canvas not in activity bar
- [ ] adding 3 fields ,total flips done till now and average flips done/per game  and flips done in the current game till now.

Reason - to give players another motive to optimise not only on time but accuracy of there clicks also.

**Comment by chimosky** [comment]
> Ok I will edit message here, but I am thinking about generating another pr with the following features if mentors/developer agree :
> 
>     * [ ]  making a table like thing in activity canvas not in activity bar
> 
>     * [ ]  adding 3 fields ,total flips done till now and average flips done/per game  and flips done in the current game till now.
> 
> 
> Reason - to give players another motive to optimise not only on time but accuracy of there clicks also.

What is _table like thing_?

**Comment by ghost** [comment]
something like this:
```
Total Flips : 150
Avg Flips/game : 75
Current game Flips : 50
```
still deciding on what name will be given clicks/taps/flips something like this.
Could remove total flips if there are too much parameters will keep only avg and current.

**Comment by chimosky** [comment]
> still deciding on what name will be given clicks/taps/flips something like this.

Flips work just fine.

**Comment by quozl** [comment]
Please make sure you put your "why" in commit message as soon as possible next time.  I've now seen your "why" for this change, and considered it in context.  I don't think this will motivate the target audience, they are pre-numerate and pre-literate and won't understand the flip counter or the table.  For numeracy we have other activities.  This activity is focused on logic and sequence, using finger touch to screen, touchpad navigation, or mouse usage.

**Comment by ghost** [comment]
Ok it makes sense for pre-numerate as they wont understand about table.
Changed the commit message to include reason, left it in activity bar itself and corrected it to show actual flips not double.
Kindly review.
Thankyou.

**Comment by walterbender** [comment]
I agree with Quozi re asking for a "why" statement when addin a new feature. However, I think it is not out of place:
* while many users are pre-numerate, one way to develop their numeracy is to expose them to it.
* it is nice (for some users at least) to have an objective measure of progress over time.

Which would lead me to the suggestion that we keep record in the journal of flips on previous tries that can be displayed.

**Comment by quozl** [comment]
Keeping record in Journal, agreed.  Applied by hand with rewrite.

**Pull request closed without merging**
